name: CI - Build, Push and Update Image Tag

on:
  push:
    paths:
      - "frontend/backend/**"
      - ".github/workflows/**"
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: vaibhs123/backend
      HELM_VALUES_FILE: HELM/backend-chart/values.yaml

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate new image tag
        id: get_tag
        run: |
          current_tag=$(grep 'tag:' $HELM_VALUES_FILE | awk '{print $2}')
          if [[ "$current_tag" =~ ^[0-9]+$ ]]; then
            new_tag=$((current_tag + 1))
          else
            new_tag=2
          fi
          echo "✅ Current tag: $current_tag"
          echo "✅ New tag: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image with new tag
        run: |
          cd frontend/backend
          docker build -t $IMAGE_NAME:${{ steps.get_tag.outputs.new_tag }} .

      - name: Push Docker Image with new tag
        run: |
          docker push $IMAGE_NAME:${{ steps.get_tag.outputs.new_tag }}

      - name: Pull image to verify it pushed correctly
        run: |
          docker pull $IMAGE_NAME:${{ steps.get_tag.outputs.new_tag }}

      - name: Update tag in Helm values.yaml
        run: |
          sed -i 's/tag: .*/tag: '"${{ steps.get_tag.outputs.new_tag }}"'/' $HELM_VALUES_FILE

      - name: Show updated values.yaml
        run: |
          cat $HELM_VALUES_FILE
