name: Push Test

on:
  push:
    paths:
      - "**/dummy.txt"

jobs:
  test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Modify dummy file
        run: |
          echo "Updated at $(date)" >> dummy.txt

      - name: Commit and push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://Dojaro433:${GH_PAT}@github.com/Dojaro433/two-tier-react-app.git

          git add dummy.txt
          git commit -m "Test push from PAT" || echo "No changes"

          # ✅ Show which remote is actually being used
          git remote -v

          git push origin HEAD:main
